on: [push, pull_request]
name: upgrade
jobs:
  upgrade:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        application: ['ojs','omp','ops']
        dataset-branch: [ 'stable-3_4_0','stable-3_3_0','stable-3_2_1','stable-3_2_0' ]
        database: [ 'pgsql','mysql']
        php-version: [ '8.1' ]
      
    name: upgrade
    steps:
      - uses: withanage/upgrade-action@v1
        with:
          application:  ${{matrix.application}}
          repository: 'pkp'
          branch: 'main' 
  